### ISSUE TITLE
Virtual Keyboard is messing device lock

### ISSUE THREAD

**Issue by cael-gomes** [tgalal/wazapp#94]
Problem: Wazapp's virtual keyboard is messing the device lock screen.
Version: Cepi's file: wazapp-29082012-1330.deb

To reproduce this bug:
1. Set device log to Settings> Security > Device Lock > Autolock > No delay
   Also set a security code.
2. Open a wazapp conversation. Enable the virtual keyboard (as image shows: http://img696.imageshack.us/img696/6636/wazappmsg.png)
3. Lock the device (press the side button on the device)
4. Try to unlock the device (double tap)
   Result: There will be a virtual keyboard over device's default lock screen (Check screenshot: http://img15.imageshack.us/img15/1696/devicelock.png)

Cael

**Comment by cael-gomes** [comment]
I can reproduce this error in Cepi's newer version also: wazapp-30082012-1630.deb

**Comment by cael-gomes** [comment]
Also tried to remove wazapp (apt-get remove wazapp), clean .db, then install wazapp-30082012-1630.deb again, and the problem continues.

**Comment by ghost** [comment]
I can reproduce the bug using CepiPerez's latest version wazapp-03092012-1225.deb

**Comment by CepiPerez** [comment]
Can you try if it's fixed in build 11092012-0000?

**Comment by cael-gomes** [comment]
Yes, it's fixed.

Thank you!

**Comment by mbanck** [comment]
It is still present in 0.9.13 and I don't see a related commit to the master branch
